### ISSUE TITLE
Ну умеет качать фото тикток

### ISSUE THREAD

**Issue by panikajoreserv** [anekobtw/youtube-dl-bot#2]
Надо сделать заглушку тогда что бот не умеет качать фото
а то он выплёвывает такую инфу 
![image](https://github.com/user-attachments/assets/50ca2290-0cf2-417f-a4f3-e914a1406dd0)

`WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://www.tiktok.com/@krystyna_ch/photo/7449352227094826262?_d=secCgYIASAHKAESPgo8Xt2SBXC1ckwK0Hgs8%2F8BRrPObiF8cUz8qd%2F4Gi57hb1SVl7EOYtev6FbHFXYsFDNdFn6C%2Fn1ZAdoFE3mGgA%3D&_r=1&checksum=9713fbccd2272bc8db275aca068f4fa1b9257a7fcfbe6364ec1701266e1cdd14&link_reflow_popup_iteration_sharer=%7B%22dynamic_cover%22%3A1%2C%22profile_clickable%22%3A1%2C%22click_empty_to_play%22%3A1%2C%22follow_to_play_duration%22%3A-1%7D&preview_pb=0&sec_user_id=MS4wLjABAAAAV_lLy_Mo-lkWg62-nq5AaJOLrxSCp8vm9P7EIk0D_74rzxPfUuFeHlXaIWwA5F8O&share_app_id=1233&share_item_id=7449352227094826262&share_link_id=760C5D89-7C7A-4595-8410-B7733E85F605&sharer_language=ru&social_share_type=14&source=h5_m&timestamp=1734507361&tt_from=copy&u_code=da4m33eg6md41f&ug_btm=b5836%2Cb2001&ug_photo_idx=1&user_id=6776347260244640774&utm_campaign=client_share&utm_medium=ios&utm_source=copy`

**Comment by anekobtw** [comment]
Пофиксил в последнем обновлении

[d95c60c](https://github.com/anekobtw/youtube-dl-bot/commit/d95c60c581c64297bc0e24cfba20ede7a2ff93f1)
